BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION


IF  EXISTS (SELECT * FROM sys.tables
   WHERE name = N'Tmp_INSTALACION_LOG_ERROR' AND type = 'U') 
   BEGIN
   DROP TABLE dbo.Tmp_INSTALACION_LOG_ERROR
   END

CREATE TABLE dbo.Tmp_INSTALACION_LOG_ERROR
	(
	FECHA_HORA datetime NULL,
	CODIGOHOT varchar(5) NULL,
	PROCEDIMIENTO varchar(50) NULL,
	CODIGO varchar(50) NULL,
	ERROR varchar(200) NULL
	
	)  ON [PRIMARY]

ALTER TABLE dbo.Tmp_INSTALACION_LOG_ERROR SET (LOCK_ESCALATION = TABLE)


IF  EXISTS (SELECT * FROM sys.tables
   WHERE name = N'INSTALACION_LOG_ERROR' AND type = 'U') 
   BEGIN
       IF EXISTS(SELECT * FROM dbo.INSTALACION_LOG_ERROR)
	 
	  EXEC('INSERT INTO dbo.Tmp_INSTALACION_LOG_ERROR (FECHA_HORA, CODIGOHOT, PROCEDIMIENTO, CODIGO, ERROR)
		SELECT FECHA_HORA, CODIGOHOT, PROCEDIMIENTO, CODIGO, ERROR FROM dbo.INSTALACION_LOG_ERROR WITH (HOLDLOCK TABLOCKX)')

       DROP TABLE dbo.INSTALACION_LOG_ERROR
    END
  
EXECUTE sp_rename N'dbo.Tmp_INSTALACION_LOG_ERROR', N'INSTALACION_LOG_ERROR', 'OBJECT' 
      
COMMIT


